# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: 'my-pool'

variables:
  buildConfiguration: 'Release'

steps:

# - task: UseDotNet@2
#   displayName: 'Use .NET SDK 9.x'
#   inputs:
#     packageType: sdk
#     version: '9.x'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: echo "AAAAAAAAAAAAAAAA - $(Build.BinariesDirectory)"
  displayName: 'Debug printout'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - Release'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    zipAfterPublish: true

#- script: sbom-tool generate -b .\bin\Release\net9.0\ -bc . -pn "MyConsoleApp" -pv "1.0.0" -ps "Evidente" -nsb "https://evidente.se/sbom" -pm
- script: sbom-tool generate -b $(Build.ArtifactStagingDirectory)/$(buildConfiguration) -bc . -pn "MyConsoleApp" -pv "1.0.0" -ps "Evidente" -nsb "https://evidente.se/sbom" -pm
  displayName: 'Generate SBOM'

- script: tree $(Agent.WorkFolder) /F
  displayName: 'Debug printout'

- script: trivy sbom $(Build.ArtifactStagingDirectory)\$(buildConfiguration)\_manifest\spdx_2.2\manifest.cdx.json

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()